"""Generate the bundled synthetic fixture clips + labels.json (deterministic).

Run from the repo root:  python src/turntune/data/_generate.py

Each clip alternates "speech" (band-limited modulated noise — clearly above the noise
floor) with labelled silences. The FINAL silence is the true end of turn (eot); earlier
silences are mid-turn holds — mirroring eot-bench's ground-truth convention. These are
structural fixtures for offline CI + a smoke-test UI, not realistic speech, so a real
VAD won't classify the noise as speech; the real evaluation uses eot-bench.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import soundfile as sf

SR = 16_000
HERE = Path(__file__).resolve().parent / "fixtures"
RNG = np.random.default_rng(20260603)

# (id, [(kind, seconds, label_or_None), ...])  kind in {"speech","silence"}
CLIPS = [
    (
        "fix_01_one_hold",
        [
            ("speech", 2.0, None),
            ("silence", 0.8, "hold"),
            ("speech", 1.2, None),
            ("silence", 1.0, "eot"),
        ],
    ),
    (
        "fix_02_two_holds",
        [
            ("speech", 1.5, None),
            ("silence", 0.5, "hold"),
            ("speech", 1.5, None),
            ("silence", 0.4, "hold"),
            ("speech", 1.6, None),
            ("silence", 1.5, "eot"),
        ],
    ),
    (
        "fix_03_no_holds",
        [
            ("speech", 1.8, None),
            ("silence", 1.2, "eot"),
        ],
    ),
]


def _speech(n: int) -> np.ndarray:
    noise = RNG.normal(0, 1, n).astype(np.float32)
    t = np.arange(n) / SR
    env = 0.5 + 0.5 * np.abs(np.sin(2 * np.pi * 3.0 * t))  # 3 Hz syllable-ish modulation
    return (noise * env * 0.3).astype(np.float32)


def _silence(n: int) -> np.ndarray:
    return RNG.normal(0, 1, n).astype(np.float32) * 0.0015  # tiny noise floor


def build() -> None:
    HERE.mkdir(parents=True, exist_ok=True)
    scenarios = []
    for clip_id, segs in CLIPS:
        audio, spans, t = [], [], 0.0
        for kind, secs, label in segs:
            n = int(round(secs * SR))
            audio.append(_speech(n) if kind == "speech" else _silence(n))
            if kind == "silence" and label:
                spans.append({"start": round(t, 3), "end": round(t + secs, 3), "label": label})
            t += secs
        sf.write(str(HERE / f"{clip_id}.wav"), np.concatenate(audio), SR, subtype="PCM_16")
        eot = [s for s in spans if s["label"] == "eot"]
        scenarios.append(
            {
                "id": clip_id,
                "language": "en",
                "wav": f"{clip_id}.wav",
                "duration": round(t, 3),
                "silence_spans": spans,
                "true_eot_s": eot[-1]["start"] if eot else round(t, 3),
            }
        )

    labels = {
        "_comment": "Generated by src/turntune/data/_generate.py. Final silence span = "
        "eot (true end of turn); earlier silences = hold (mid-turn pauses).",
        "scenarios": scenarios,
    }
    (HERE / "labels.json").write_text(json.dumps(labels, indent=2) + "\n")
    print(f"wrote {len(scenarios)} fixtures + labels.json to {HERE}")


if __name__ == "__main__":
    build()
